### ISSUE TITLE
Optional Prometheus URL Possible

### ISSUE THREAD

**Issue by Lewiscowles1986** [johnmccabe/openfaas-bitbar#2]
What would it take to allow turning off metrics via Prometheus?

config.yaml currently has optional auth parameters, I was thinking that optional Prometheus parameter could make this more portable as a config file format.

I Know how easy it is for config as I've used it in a project and patched my copy. What I'm unsure of is how easy to provision it is for the bitbar-cli

**Comment by johnmccabe** [comment]
The BitBar app will be updated to pull in config from the updates that @stefanprodan is in the middle of making.

**Comment by johnmccabe** [comment]
What is the rationale for turning this off?

**Comment by Lewiscowles1986** [comment]
Allowing update from one place and not showing Prometheus metrics if the parameter is missing from the config.

**Comment by johnmccabe** [comment]
> Allowing update from one place 

I'm afraid I don't quite follow what you mean here?

**Comment by Lewiscowles1986** [comment]
Looks like #3 answers this, I'll close. What I meant was why have the functionality to take gateway URL's if it's available from openfaas-cli (where deploys etc come from), reduce or remove so it's straightforward and there is one clear place to handle. Thank you though.
