### ISSUE TITLE
Deprecate / drop credentials update

### ISSUE THREAD

**Issue by Lewiscowles1986** [johnmccabe/openfaas-bitbar#3]
Right now I can set credentials in openfaas-bitbar. Once openfaas-cli gets login command and functionality, would it make sense to break config into a single shared repo to lower development overlap between openfaas-cli and openfaas-bitbar? 

If so then you can define and load a config file using a shared lib, defer the storage of credentials to the official openfaas-cli, but would have no reason to write to it from openfaas-bitbar.

**Comment by johnmccabe** [comment]
The BitBar app will be updated to pull in config from the updates that @stefanprodan is in the middle of making.
